Add more linters and address related issues
wakatime/wakatime-cli pull request #835
Opened 2023-02-15 07:27 UTC by hezhizhen

2023-02-15 07:28 UTC, hezhizhen commented
Close https://github.com/wakatime/wakatime-cli/pull/834 with correct branch name

2023-02-16 07:18 UTC, hezhizhen commented
I need some help to pass unit tests on Windows @alanhamlett @gandarez

2023-02-16 08:37 UTC, alanhamlett commented
I re-ran that test and it passed the second time. On Windows, sometimes the GitHub Action fails to install the linter and we just re-run it.

2023-02-16 08:41 UTC, hezhizhen commented
> I re-ran that test and it passed the second time. On Windows, sometimes the GitHub Action fails to install the linter and we just re-run it.

Thanks.

2023-02-16 08:47 UTC, alanhamlett commented
LGTM, but I'll wait for @gandarez to make the final decision before merging.

2023-02-16 10:35 UTC, gandarez requested changes

2023-02-16 10:35 UTC, gandarez commented on .golangci.yml
> +    - unparam
Unused params is already set using `revive:unused-parameter`

2023-02-16 10:35 UTC, gandarez commented on .golangci.yml
> +    - gosimple
It's enabled by default, so don't need to explicitly set here.

2023-02-16 10:35 UTC, gandarez commented on .golangci.yml
> +    - unused
It's enabled by default, so don't need to explicitly set here.

2023-02-16 10:42 UTC, hezhizhen commented
I removed the 3 linters. @gandarez

2023-02-16 12:14 UTC, gandarez approved these changes

2023-02-16 12:14 UTC, merged